name: generic_bash

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generic_bash:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      #### actions/checkout ____________________________________________________
      # @see https://github.com/actions/checkout
      - uses: actions/checkout@v3

      #### bash setup __________________________________________________________
      # Already installed

      #### main ________________________________________________________________
      - run: bash .github/scripts/salve_mundi.sh

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
