name: generic_perl

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generic_perl:
    runs-on: ubuntu-latest
    # continue-on-error: true
    steps:
      #### actions/checkout ____________________________________________________
      # @see https://github.com/actions/checkout
      - uses: actions/checkout@v3

      #### bash setup __________________________________________________________
      # Likely already installed (if Linux runner)
      # @TODO maybe test https://github.com/perl-actions/install-with-cpanm

      #### main ________________________________________________________________
      - run: perl .github/scripts/salve_mundi.pl
