# WORKING DRAFT; not full implemented

name: generic_gdal

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generic_gdal:
    runs-on: ubuntu-latest
    # runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      #### actions/checkout ____________________________________________________
      # @see https://github.com/actions/checkout
      - uses: actions/checkout@v3

      #### setup-conda __________________________________________________
      # @see https://github.com/conda-incubator/setup-miniconda
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          # activate-environment: foo
          # python-version: 3.10
          python-version: 3.9

      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show

      #### Setup geopandas __________________________________________________
      # @see https://geopandas.org/

      - run: conda install geopandas

      #### main ________________________________________________________________
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show

### temp
# https://gis.stackexchange.com/questions/370736/installing-gdal-on-ubuntu-20-04-unmet-dependencies
# https://launchpad.net/~ubuntugis/+archive/ubuntu/ppa